name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeding
        run: echo "hello w"
      - name: Print goodby
        run: echo "Done - bye"
